# Equal-Weight S&P 500 Index Fund

## Introduction & Library Imports

The NIFTY 50 is a benchmark Indian stock market index that represents the weighted average of 50 of the largest Indian companies listed on the National Stock Exchange. Nifty 50 is owned and managed by NSE Indices, which is a wholly owned subsidiary of the NSE Strategic Investment Corporation Limited. 


The goal of this project is to create a Python script that will accept the value of your portfolio and tell you how many shares of each Nifty50 constituent you should purchase to get an equal-weight version of the index fund.

The project is inspired from the help of  algorithmic-trading-python by Nick Mccullum and with the help of youtube channel Financial Programming with Ritvik, CFA

# Library Imports

In [18]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import numpy as np
import math

# Importing our list of stocks(NIFTY50)

In [33]:
df=pd.read_csv("pythonprojects/ind_nifty50list.csv")

# Making our first API Call

We do this to get to know about the classes of price and market cap for future use.

In [34]:
ticker="IRFC"
url=f"https://www.google.com/finance/quote/{ticker}:NSE?hl=en"
response=requests.get(url)
soup=BeautifulSoup(response.text,'html.parser')

Hence class1 will be the price class and class2 will be the marketcap class

In [35]:
class1="YMlKec fxKbKc"
# price=float(soup.find(class_=class1).text.strip()[1:])
# # price

In [36]:
class2="P6K39c"
# marketcap=soup.find_all(class_=class2)
# marketcap=float(marketcap[3].text.strip()[:4])
# # marketcap

# Creating our Dataframe

In [37]:
my_columns=["Ticker","Price","Market Capitalization(Trillions)","Number of Shares to Buy"]

In [38]:
final_dataframe = pd.DataFrame(columns = my_columns)

# Looping Through The Tickers in Our List of Stocks and Adding them in our Dataframe

In [40]:
for ticker in df['Symbol']:
    url=f"https://www.google.com/finance/quote/{ticker}:NSE?hl=en"
    response=requests.get(url)
    soup=BeautifulSoup(response.text,'html.parser')
    price=float(soup.find(class_=class1).text.strip()[1:].replace(',', ''))
    marketcap=soup.find_all(class_=class2)
    marketcap=float(marketcap[3].text.strip()[:4])
    if(marketcap>100):
        marketcap/=100
    final_dataframe.loc[len(final_dataframe)] = [ticker,
                                                   price, 
                                                marketcap, 
                                                   'N/A']
final_dataframe

,Ticker,Price,Market Capitalization(Trillions),Number of Shares to Buy
0,ADANIENT,3332.50,3.80,N/A
1,ADANIPORTS,1336.15,2.89,N/A
2,APOLLOHOSP,6133.80,8.81,N/A
3,ASIANPAINT,2849.20,2.73,N/A
4,AXISBANK,1095.25,3.38,N/A
5,BAJAJ-AUTO,8045.00,2.28,N/A
6,BAJFINANCE,6588.00,4.07,N/A
7,BAJAJFINSV,1611.05,2.56,N/A
8,BPCL,625.00,1.35,N/A
9,BHARTIARTL,1133.00,6.68,N/A
10,BRITANNIA,4914.95,1.18,N/A
11,CIPLA,1483.00,1.20,N/A
12,COALINDIA,448.55,2.76,N/A
13,DIVISLAB,3512.80,9.32,N/A
14,DRREDDY,6240.00,1.04,N/A
15,EICHERMOT,3858.00,1.06,N/A
16,GRASIM,2248.00,1.55,N/A
17,HCLTECH,1648.50,4.46,N/A
18,HDFCBANK,1430.95,10.80,N/A
19,HDFCLIFE,591.95,1.27,N/A
20,HEROMOTOCO,4578.00,9.15,N/A
21,HINDALCO,523.90,1.17,N/A
22,HINDUNILVR,2414.05,5.67,N/A
23,ICICIBANK,1083.90,7.61,N/A
24,ITC,412.00,5.14,N/A
25,INDUSINDBK,1527.50,1.19,N/A
26,INFY,1655.20,6.85,N/A
27,JSWSTEEL,844.00,2.06,N/A
28,KOTAKBANK,1724.80,3.43,N/A
29,LTIM,5295.25,1.56,N/A
30,LT,3652.90,5.02,N/A
31,M&M,1959.80,2.35,N/A
32,MARUTI,11545.00,3.63,N/A
33,NTPC,341.80,3.31,N/A
34,NESTLEIND,2590.00,2.50,N/A
35,ONGC,271.40,3.42,N/A
36,POWERGRID,287.00,2.67,N/A
37,RELIANCE,2980.95,20.10,N/A
38,SBILIFE,1546.90,1.55,N/A
39,SBIN,773.70,6.90,N/A
40,SUNPHARMA,1552.00,3.72,N/A
41,TCS,4110.00,14.80,N/A
42,TATACONSUM,1207.00,1.15,N/A
43,TATAMOTORS,989.00,3.62,N/A
44,TATASTEEL,155.35,1.94,N/A
45,TECHM,1271.90,1.24,N/A
46,TITAN,3765.95,3.34,N/A
47,UPL,476.40,3.57,N/A
48,ULTRACEMCO,10095.00,2.91,N/A
49,WIPRO,523.00,2.73,N/A

# Taking The Porfolio Size As Input And Recommending As Per Portfolio

In [41]:
portfolio_size = input("Enter the value of your portfolio:")

Enter the value of your portfolio: 70000

## Caluclating The Number Of Shares To Buy

In [42]:
position_size = float(portfolio_size) / len(final_dataframe.index)
position_size
for i in range(0, len(final_dataframe['Ticker'])):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe['Price'][i])

In [44]:
final_dataframe

,Ticker,Price,Market Capitalization(Trillions),Number of Shares to Buy
0,ADANIENT,3332.50,3.80,0
1,ADANIPORTS,1336.15,2.89,1
2,APOLLOHOSP,6133.80,8.81,0
3,ASIANPAINT,2849.20,2.73,0
4,AXISBANK,1095.25,3.38,1
5,BAJAJ-AUTO,8045.00,2.28,0
6,BAJFINANCE,6588.00,4.07,0
7,BAJAJFINSV,1611.05,2.56,0
8,BPCL,625.00,1.35,2
9,BHARTIARTL,1133.00,6.68,1
10,BRITANNIA,4914.95,1.18,0
11,CIPLA,1483.00,1.20,0
12,COALINDIA,448.55,2.76,3
13,DIVISLAB,3512.80,9.32,0
14,DRREDDY,6240.00,1.04,0
15,EICHERMOT,3858.00,1.06,0
16,GRASIM,2248.00,1.55,0
17,HCLTECH,1648.50,4.46,0
18,HDFCBANK,1430.95,10.80,0
19,HDFCLIFE,591.95,1.27,2
20,HEROMOTOCO,4578.00,9.15,0
21,HINDALCO,523.90,1.17,2
22,HINDUNILVR,2414.05,5.67,0
23,ICICIBANK,1083.90,7.61,1
24,ITC,412.00,5.14,3
25,INDUSINDBK,1527.50,1.19,0
26,INFY,1655.20,6.85,0
27,JSWSTEEL,844.00,2.06,1
28,KOTAKBANK,1724.80,3.43,0
29,LTIM,5295.25,1.56,0
30,LT,3652.90,5.02,0
31,M&M,1959.80,2.35,0
32,MARUTI,11545.00,3.63,0
33,NTPC,341.80,3.31,4
34,NESTLEIND,2590.00,2.50,0
35,ONGC,271.40,3.42,5
36,POWERGRID,287.00,2.67,4
37,RELIANCE,2980.95,20.10,0
38,SBILIFE,1546.90,1.55,0
39,SBIN,773.70,6.90,1
40,SUNPHARMA,1552.00,3.72,0
41,TCS,4110.00,14.80,0
42,TATACONSUM,1207.00,1.15,1
43,TATAMOTORS,989.00,3.62,1
44,TATASTEEL,155.35,1.94,9
45,TECHM,1271.90,1.24,1
46,TITAN,3765.95,3.34,0
47,UPL,476.40,3.57,2
48,ULTRACEMCO,10095.00,2.91,0
49,WIPRO,523.00,2.73,2